version: "3.2"
networks:
  netaxe-ipam-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.169.205.0/24

services:
  netaxeipam_server:
    image: registry.cn-shanghai.aliyuncs.com/net-axe/axe-ipam:1.0.2
    container_name: netaxeipam_server
    ports:
      - "38001:38001"
    command: sh start.sh web
    volumes:
      - ../netaxe_ipam:/home/netaxeipam/
      - ./netaxeipam/logs/netaxeipam_log:/home/netaxeipam/logs
    networks:
      - netaxe-ipam-network

  netaxeipam_nginx:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/nginx:1.7.9
    container_name: netaxeipam_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ../netaxe_ipam:/home/netaxeipam/
    ports:
      - "39999:39999"
    depends_on:
      - netaxeipam_server
    networks:
      - netaxe-ipam-network

  celery_netaxe_ipam:
    image: registry.cn-shanghai.aliyuncs.com/net-axe/axe-ipam:1.0.2
    container_name: celery_netaxe_ipam
    command: sh start.sh netaxe_ipam
    depends_on:
      - netaxeipam_server
    volumes:
      - ../netaxe_ipam:/home/netaxeipam
    networks:
      - netaxe-ipam-network


  ipam-mysql-server:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/mysql:5.7
    restart: always
    container_name: ipam-mysql-server
    environment:
      TZ: Asia/Shanghai
      MYSQL_USER: "netaxe"
      MYSQL_DATABASE: "netaxe_ipam"
      MYSQL_ROOT_PASSWORD: "root_devnet@2022"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    ports:
      - "8306:3306"
    networks:
      - netaxe-ipam-network