version: "3.2"
networks:
  django_open-ipam-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.169.205.0/24

services:
  django_openipam_server:
    image: registry.cn-shanghai.aliyuncs.com/net-axe/axe-ipam:1.0.2
    container_name: django_openipam_server
    ports:
      - "38001:38001"
    command: sh start.sh web
    volumes:
      - ../django_open_ipam:/home/django_openipam/
      - ./django_openipam/logs/django_openipam_log:/home/django_openipam/logs
    networks:
      - django_open-ipam-network

  django_openipam_nginx:
    image: registry.cn-hangzhou.aliyuncs.com/django_open/nginx:1.7.9
    container_name: django_openipam_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ../django_open_ipam:/home/django_openipam/
    ports:
      - "39999:39999"
    depends_on:
      - django_openipam_server
    networks:
      - django_open-ipam-network

  celery_django_open_ipam:
    image: registry.cn-shanghai.aliyuncs.com/net-axe/axe-ipam:1.0.2
    container_name: celery_django_open_ipam
    command: sh start.sh django_open_ipam
    depends_on:
      - django_openipam_server
    volumes:
      - ../django_open_ipam:/home/django_openipam
    networks:
      - django_open-ipam-network


  ipam-mysql-server:
    image: registry.cn-hangzhou.aliyuncs.com/django_open/mysql:5.7
    restart: always
    container_name: ipam-mysql-server
    environment:
      TZ: Asia/Shanghai
      MYSQL_USER: "django_open"
      MYSQL_DATABASE: "django_open_ipam"
      MYSQL_ROOT_PASSWORD: "root_devnet@2022"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    ports:
      - "8306:3306"
    networks:
      - django_open-ipam-network